# Generated by Django 6.0.7 on 2026-08-04 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='과목/주제')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='공부 시간(분)')),
                ('memo', models.TextField(blank=True, verbose_name='학습 내용 및 메모')),
                ('is_public', models.BooleanField(default=False, verbose_name='커뮤니티 공유 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=150, verbose_name='한줄 소개')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='공부 분야/전공')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
