# Generated by Django 6.0.7 on 2026-08-23 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
